### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by rzr** [Z-Wave-Alliance/z-wave-pc-controller#10]
- [x] Should be build from CI : https://github.com/Z-Wave-Alliance/z-wave-pc-controller/issues/7
  -  https://github.com/Z-Wave-Alliance/z-wave-pc-controller/pull/14
- [x] Dependencies should be pined: https://github.com/Z-Wave-Alliance/z-wave-tools-core/issues/11
   - https://github.com/Z-Wave-Alliance/z-wave-pc-controller/pull/13
- [x] Package should contain licensing files
  - https://github.com/Z-Wave-Alliance/z-wave-pc-controller/pull/14 (can be improved once dep is pulled in)
- [x] Test on Linux/wine @rzr @bstewart-cae 
- [x] Version scheme should be established, since there is no API per say here we might prefer CalVer over SemVer (v25.01 could be a good candidate)
  - https://github.com/Z-Wave-Alliance/OSWG/discussions/49
  - https://github.com/Z-Wave-Alliance/z-wave-pc-controller/pull/15
  - Note MS standard seems to be 4 numbers, we will had .0 as {Modifier} suffix
- [ ] xml files to come from upstream 
  - will be relaxed for 1st iteration import release
  - https://github.com/Z-Wave-Alliance/z-wave-pc-controller/issues/16
- [ ] Package can be signed by @ZWA-Admin :  https://github.com/Z-Wave-Alliance/OSWG/issues/48
  -  will be relaxed for 1st iteration import release
- [x] Public release https://github.com/Z-Wave-Alliance/OSWG/discussions/41
  -  will be relaxed for 1st iteration import release
- [ ] Consider removal of blob if possible
  - https://github.com/Z-Wave-Alliance/z-wave-pc-controller/issues/8

Any other step missing ?
